version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "127.0.0.1:8080:80"
    volumes:
    - ./templates:/etc/nginx/templates
    - ./static:/usr/share/nginx/html
    environment:
        - NGINX_HOST=rsvbotdigitalleader.ml
        - NGINX_PORT=80
    